services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  service-b:
    build:
      context: ./service-b
      dockerfile: ./app/Dockerfile
    container_name: service-b
    ports:
      - "8001:8001"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  service-a:
    build:
      context: ./service-a
      dockerfile: ./app/Dockerfile
    container_name: service-a
    ports:
      - "8000:8000"
    depends_on:
      - service-b
